changing locations

diff --git a/.github/workflows/dbt_ci_cd.yml b/.github/workflows/dbt_ci_cd.yml
--- a/.github/workflows/dbt_ci_cd.yml
+++ b/.github/workflows/dbt_ci_cd.yml
@@ -47,8 +47,7 @@ jobs:
 
     - name: Copy manifest.json from Google Cloud Storage
       run: |
-        mkdir -p target_prod
-        gsutil cp gs://${{ env.GCLOUD_STORAGE_PATH_MANIFEST }}/manifest.json target_prod/ || echo "Manifest not found"
+        gsutil cp gs://${{ env.GCLOUD_STORAGE_PATH_MANIFEST }}/manifest.json ./ || echo "Manifest not found"
 
     - name: Run dbt debug for PRs
       if: github.event_name == 'pull_request'
@@ -64,8 +63,8 @@ jobs:
     - name: Run dbt build for PRs
       if: github.event_name == 'pull_request'
       run: |
-        if [ -f "target_prod/manifest.json" ]; then
-          dbt build -s 'state:modified+' --defer target_prod --target dev
+        if [ -f "./manifest.json" ]; then
+          dbt build -s 'state:modified+' --defer ./ --target dev
         else
           dbt build --target dev
         fi
@@ -73,13 +72,13 @@ jobs:
     - name: Run dbt build for main branch
       if: github.ref == 'refs/heads/main'
       run: |
-        if [ -f "target_prod/manifest.json" ]; then
-          dbt build -s 'state:modified+' --defer target_prod --target prod
+        if [ -f "./manifest.json" ]; then
+          dbt build -s 'state:modified+' --defer ./ --target prod
         else
           dbt build --target prod
         fi
 
     - name: Copy new manifest.json to Google Cloud Storage
       run: |
-        gsutil cp target/manifest.json gs://${{ env.GCLOUD_STORAGE_PATH_MANIFEST }}/
+        gsutil cp ./target/manifest.json gs://${{ env.GCLOUD_STORAGE_PATH_MANIFEST }}/
       if: github.event_name == 'push'
